---
title: "Cannabis"
author: "Mike"
date: '2022-06-09'
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(readxl)
library(tidyr)

```

```{r}
# Read file
cannabis_file <- read_excel("Cannabis info.xlsx")
```

```{r}
cannabis_file <- cannabis_file %>%
    select(-Labels, -Content)
```

```{r}
snp_assay <- as.vector(cannabis_file$`Snps Assay`)
snp_assay <- snp_assay[!is.na(snp_assay)] # remove all NA's
```


```{r}
for (i in 1:length(snp_assay)) {
    cannabis_file <- cannabis_file %>%
        mutate(a = "NA")
    colnames(cannabis_file)[colnames(cannabis_file) == "a"] <-      snp_assay[i]
}
```

```{r}
cannabis_file <- cannabis_file %>%
    select(-`Snps Assay`)
```

```{r}
SNP <- as.vector(cannabis_file$SNPS)
for (i in 1:length(SNP)){
  one_SNP <- SNP[i]
  one_SNP <- strsplit(one_SNP, split="")
  for (j in 1:length(one_SNP[[1]])) {
    cannabis_file[i, j + 4] <- one_SNP[[1]][j]
  }
}
cannabis_file <- cannabis_file %>%
    select(-SNPS)
```

```{r}
cannabis_file <- cannabis_file %>%
    separate('THC/CBD', sep = "/", into = c("THC", "CBD"))
cannabis_file$CBD[is.na(cannabis_file$CBD)] <- "NA"
```

```{r}
cannabis_file <- cannabis_file %>%
    separate(THC, sep = ",", into = c("THC total", "THC")) %>%
      separate(CBD, sep = ",", into = c("CBD total", "CBD"))
```

```{r}
getNum <- function(value){
  for (i in 1:length(value)){
  value[i] <- as.numeric(sub("%","",(strsplit(value[i], split=":")[[1]][2])))/100
  }
  return (value)
}

cannabis_file$`THC total` <- getNum(cannabis_file$`THC total`)
cannabis_file$THC <- getNum(cannabis_file$THC)
cannabis_file$`CBD total` <- getNum(cannabis_file$`CBD total`)
cannabis_file$CBD <- getNum(cannabis_file$CBD)
View(cannabis_file)
```
